apiVersion: apps/v1
kind: Deployment
metadata:
  name:  disney-hotstar-deploy
  namespace: default
  labels:
    app:  disney-hotstar
spec:
  selector:
    matchLabels:
      app: disney-hotstar
  replicas: 2
  template:
    metadata:
      labels:
        app:  disney-hotstar
    spec:
      containers:
      - name:  disney-hotstar-container
        image:  752948842505.dkr.ecr.ap-south-1.amazonaws.com/disney-hostart-ecr-repo:21
        imagePullPolicy: Always
        ports:
        - containerPort:  80
      restartPolicy: Always

---

Kind: # https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: disney-hotstar-svc
  namespace: default
spec:
  selector:
    app: disney-hotstar
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  

